<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var SecureHtmlRenderer $secureRenderer */

$script = <<<SCRIPT
    document.addEventListener('alpine:init', () => {
        Alpine.data('MiniCart', () => ({
            cart: {},
            loading: false,
            contentVisible: false,
            init() {
                Alpine.effect(() => {
                    this.cart = Alpine.store('LocalStorage').get('cart');
                });
            },
            toggleContentVisible() {
                this.contentVisible = !this.contentVisible;
            },
            getCartSummaryCount() {
                if (!this.cart) {
                    return 0;
                }

                if (this.cart.summary_count > 0) {
                    return this.cart.summary_count;
                }
            },
            qtyClass() {
                if (!this.cart) {
                    return 'empty';
                }

                return this.cart.summary_count > 0 ? '' : 'empty';
            },
            proceedToCheckout() {
                window.location = '{$block->getUrl(
                    'checkout'
                )}';
            },
            toggleCartItemButton() {
                const cartItemOriginalQty = parseInt(this.\$el.getAttribute('data-cart-item-qty'));
                const cartItemNewQty = parseInt(this.\$el.value);
                const cartItemButton = this.\$el.parentNode.querySelector('button');
                cartItemButton.style.display = (cartItemNewQty !== cartItemOriginalQty) ? 'inline-block' : 'none';
            },
            updateCartItemQty() {
                const cartItemId = this.\$el.getAttribute('data-cart-item-id');
                const cartItemInput = document.getElementById('cart-item-' + cartItemId + '-qty');
                const cartItemQty = parseInt(cartItemInput.value);
                const cartItem = this.cart.items.find((item) => item.item_id === cartItemId);
                const currentQty = parseInt(cartItem.qty);

                if (currentQty === cartItemQty) {
                    return;
                }

                const ajaxUpdateUrl = '{$block->getUrl(
                    'checkout/sidebar/updateItemQty'
                )}';

                this.loading = true;
                fetch(ajaxUpdateUrl, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
                    },
                    body: new URLSearchParams({
                        'item_id': cartItemId,
                        'item_qty': cartItemQty,
                        'form_key': window.FORM_KEY
                    })
                })
                    .then(response => response.json())
                    .then(data => {
                        Alpine.store('LocalStorage').refresh('cart,messages', true);

                        Alpine.store('Message').addNoticeMessage('{$escaper->escapeHtml(
                            __('Updated quantity')
                        )}');

                        this.loading = false;
                    });
            },
            hasCartItems() {
                if (!this.cart || !this.cart.items) {
                    return false;
                }

                return this.cart.items.length > 0;
            },
            hasNoCartItems() {
                return !this.hasCartItems();
            },
            removeCartItem(event) {
                const cartItemId = this.\$el.getAttribute('data-cart-item');

                const ajaxUpdateUrl = '{$block->getUrl(
                    'checkout/sidebar/removeItem'
                )}';

                this.loading = true;
                fetch(ajaxUpdateUrl, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
                    },
                    body: new URLSearchParams({
                        'item_id': cartItemId,
                        'form_key': window.FORM_KEY
                    })
                })
                    .then(response => response.json())
                    .then(data => {
                        Alpine.store('LocalStorage').refresh('cart,messages', true);

                        Alpine.store('Message').addNoticeMessage('{$escaper->escapeHtml(
                            __('Removed item')
                        )}');

                        this.loading = false;
                    });
            }
        }));
    });
SCRIPT;
?>
<?= $secureRenderer->renderTag('script', [], $script, false); ?>
