<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use MageOS\AlpineMinicart\ViewModel\Minicart;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var SecureHtmlRenderer $secureRenderer */
/** @var Minicart $minicart */

$minicart = $block->getMinicart();
$count = (int)$minicart->count();
$maxItemsDisplayCount = $minicart->maxItemsDisplayCount();
$script = '';
$script .= 'const ALPINE_MINICART_COUNT = '.(int)$count.";\n";
$script .= 'const ALPINE_MINICART_MIN_ITEMS_DISPLAY_COUNT = '.(int)$count.";\n";
$script .= 'const ALPINE_MINICART_MAX_ITEMS_DISPLAY_COUNT = '.(int)$maxItemsDisplayCount.";\n";
$script .= 'const ALPINE_MINICART_CHECKOUT_URL = "'.$block->getUrl('checkout').'"'.";\n";
$script .= 'const ALPINE_MINICART_UPDATE_CART_ITEM_URL = "'.$block->getUrl('checkout/sidebar/updateItemQty').'"'.";\n";
$script .= 'const ALPINE_MINICART_REMOVE_CART_ITEM_URL = "'.$block->getUrl('checkout/sidebar/removeItem').'"'.";\n";
$script .= 'const ALPINE_MINICART_MESSAGE_REMOVED_ITEM = "'.__('Removed item').'"'.";\n";
$script .= 'const ALPINE_MINICART_MESSAGE_UPDATED_QTY = "'.__('Updated quantity').'"'.";\n";
$script .= file_get_contents(__DIR__.'/minicart-component.js');
?>
<?= $secureRenderer->renderTag('script', [], $script, false); ?>
